% Generated by/Last edit by
% Author:           Christian Haffner/Christian Haffner
% E-Mail:           chrisitan.haffner@ief.ee.ethz.ch
% Organization:     ETHZ ITET IEF

%% Data Evaluation
close all

% checks if parameters are available in worksepace. if false -> Opens load
% dialog
if ~exists('sim_results') || ~exists('param_list')  || ~exists('sim_results')
    % load... 
end

%% highlight available simulation results
% availabe simulation results
available_sim_results = [];
for jj = 1:length(sim_results{1})
    available_sim_results = [available_sim_results ',  ' sim_results{1}(jj).str];
end
fprintf(['************************************************************* \n'...
    'Result Names:' available_sim_results '!\n']);

% availabe parameters
available_param = [];
for jj = 1:length(param_list.str)
    available_param = [available_param ',  ' param_list.str{jj}];
end
fprintf(['************************************************************* \n'...
    'Parameter Names:' available_param '!\n']);

%%
plotResultList(sim_results, param_list,'data_str', 'g_0',...
    'para_str', {para_sweep{1}.str, 'hWG_bot' ,'wl'}, 'para_values', {[], [] ,1550e-9},...
    'data_FOM', 'max', 'save', ['./Results/' workspace_save_str]);

plotResultList(sim_results, param_list,'data_str', 'g_0',...
    'para_str', {para_sweep{1}.str, 'hWG_bot' ,'wl'}, 'para_values', {[], [] ,1900e-9},...
    'data_FOM', 'max', 'save', ['./Results/' workspace_save_str]);
%%
plotResultList(sim_results, param_list,'data_str', 'gamma',...
    'para_str', {para_sweep{1}.str, 'hWG_bot' ,'wl'}, 'para_values', {[], [] ,1550e-9},...
    'data_FOM', 'max', 'save', ['./Results/' workspace_save_str]);

plotResultList(sim_results, param_list,'data_str', 'gamma',...
    'para_str', {para_sweep{1}.str, 'hWG_bot' ,'wl'}, 'para_values', {[], [] ,1900e-9},...
    'data_FOM', 'max', 'save', ['./Results/' workspace_save_str]);

%%
plotResultList(sim_results, param_list,'data_str', 'Q', ...
    'para_str', {para_sweep{1}.str, 'hWG_bot' ,'wl'}, 'para_values', {[], [] ,1550e-9},...
    'data_FOM', 'max', 'save', ['./Results/' workspace_save_str]);

%%
plotResultList(sim_results, param_list,'data_str', 'Q', ...
    'para_str', {'wl', para_sweep{1}.str}, 'para_values', {[], []},...
    'data_FOM', 'max', 'save', ['./Results/' workspace_save_str]);