% Generated through Matlab
% Author:           Christian Haffner
% E-Mail:           christian.haffner1986@gmail.com
% Organization:     ETHZ ITET IEF/NIST

function checkDomain(materialNames, newDomain, newMaterial)
%checkDomain IF newDomain generated by an object of newMaterial is part of a
%previous materials assignement (eg exlcuding the new material.YES removes previous material assignment
    % materialNames - material containers defined by the used materials
    % newDomain - domain numbers of the newly generated file
        
    for jj = 1:length(materialNames)
        
        model.component('comp1').geom('geom1').feature('r_ThermalOxide').get('contributeto', materialNames(1))
    end

end